export type Card = {
  objective: string;
  taboos: string[];
};

export const terms = [
  {
    category: "Movies",
    cards: [
      {
        objective: "The Godfather",
        taboos: [
          "Mafia",
          "Don Corleone",
          "Marlon Brando",
          "New York",
          "Crime",
          "Family",
          "Vito",
          "Michael",
          "Godfather",
          "Offer",
        ],
      },
      {
        objective: "Star Wars",
        taboos: [
          "Jedi",
          "Darth Vader",
          "Luke Skywalker",
          "Lightsaber",
          "Force",
          "Galaxy",
          "Princess Leia",
          "Empire",
          "Han Solo",
          "Space",
        ],
      },
      {
        objective: "Jurassic Park",
        taboos: [
          "Dinosaurs",
          "T-Rex",
          "Steven Spielberg",
          "Island",
          "Adventure",
          "Prehistoric",
          "Velociraptor",
          "Fossils",
          "Park",
          "Jeff Goldblum",
        ],
      },
      {
        objective: "The Matrix",
        taboos: [
          "Neo",
          "Keanu Reeves",
          "Virtual Reality",
          "Red Pill",
          "Blue Pill",
          "Morpheus",
          "Cyberpunk",
          "Trinity",
          "Agent Smith",
          "Computer",
        ],
      },
      {
        objective: "Forrest Gump",
        taboos: [
          "Tom Hanks",
          "Vietnam War",
          "Life is like a box of chocolates",
          "Jenny",
          "Run Forrest, run",
          "Bubba",
          "Shrimp",
          "Alabama",
          "Ping Pong",
          "Lieutenant Dan",
        ],
      },
      {
        objective: "Inception",
        taboos: [
          "Dreams",
          "Leonardo DiCaprio",
          "Christopher Nolan",
          "Reality",
          "Cobb",
          "Dream within a dream",
          "Architecture",
          "Mind",
          "Heist",
          "Top",
        ],
      },
      {
        objective: "The Shawshank Redemption",
        taboos: [
          "Prison",
          "Stephen King",
          "Andy Dufresne",
          "Red",
          "Hope",
          "Escape",
          "Redemption",
          "Morgan Freeman",
          "Innocence",
          "Warden",
        ],
      },
      {
        objective: "The Lord of the Rings: The Fellowship of the Ring",
        taboos: [
          "Middle-earth",
          "Frodo Baggins",
          "Gandalf",
          "Ring",
          "Hobbits",
          "Fantasy",
          "Sauron",
          "Quest",
          "Samwise Gamgee",
          "J.R.R. Tolkien",
        ],
      },
      {
        objective: "The Dark Knight",
        taboos: [
          "Batman",
          "Joker",
          "Gotham",
          "Heath Ledger",
          "Christian Bale",
          "Superhero",
          "Crime",
          "Harvey Dent",
          "Christopher Nolan",
          "Gotham City",
        ],
      },
      {
        objective: "Pulp Fiction",
        taboos: [
          "Quentin Tarantino",
          "Vincent Vega",
          "Mia Wallace",
          "Samuel L. Jackson",
          "John Travolta",
          "Crime",
          "Violence",
          "Royale with Cheese",
          "Uma Thurman",
          "Hitmen",
        ],
      },
    ],
  },
  {
    category: "Pop Singers",
    cards: [
      {
        objective: "Michael Jackson",
        taboos: [
          "Thriller",
          "King of Pop",
          "Moonwalk",
          "Billie Jean",
          "Beat It",
          "Jackson 5",
          "Pop",
          "Dance",
          "Legend",
          "Glove",
        ],
      },
      {
        objective: "Beyoncé",
        taboos: [
          "Destiny's Child",
          "Queen Bey",
          "Formation",
          "Lemonade",
          "Single Ladies",
          "Jay-Z",
          "Sasha Fierce",
          "Formation World Tour",
          "Coachella",
          "Empowerment",
        ],
      },
      {
        objective: "Elvis Presley",
        taboos: [
          "The King",
          "Graceland",
          "Rock and Roll",
          "Blue Suede Shoes",
          "Hound Dog",
          "Jailhouse Rock",
          "Memphis",
          "Guitar",
          "Pelvis",
          "Heartbreak Hotel",
        ],
      },
      {
        objective: "Madonna",
        taboos: [
          "Material Girl",
          "Like a Virgin",
          "Queen of Pop",
          "Vogue",
          "Ray of Light",
          "Rebel Heart",
          "Ciccone",
          "Pioneer",
          "Icon",
          "Like a Prayer",
        ],
      },
      {
        objective: "Justin Bieber",
        taboos: [
          "Beliebers",
          "Purpose",
          "Baby",
          "Canada",
          "Scooter Braun",
          "Hailey Baldwin",
          "Sorry",
          "Yummy",
          "Purpose World Tour",
          "Love Yourself",
        ],
      },
      {
        objective: "Adele",
        taboos: [
          "Hello",
          "Someone Like You",
          "Rolling in the Deep",
          "21",
          "Grammy",
          "Skyfall",
          "Chasing Pavements",
          "British",
          "Soulful",
          "Voice",
        ],
      },
      {
        objective: "Taylor Swift",
        taboos: [
          "Swifties",
          "Red",
          "Fearless",
          "1989",
          "Shake It Off",
          "Blank Space",
          "Lover",
          "Country",
          "Singer-Songwriter",
          "Pop",
        ],
      },
      {
        objective: "Rihanna",
        taboos: [
          "Umbrella",
          "Rude Boy",
          "Diamonds",
          "Work",
          "Barbados",
          "Anti",
          "Fenty Beauty",
          "Fashion",
          "Savage X Fenty",
          "Navy",
        ],
      },
      {
        objective: "Ed Sheeran",
        taboos: [
          "Shape of You",
          "Thinking Out Loud",
          "Castle on the Hill",
          "The A Team",
          "Divide",
          "Ginger",
          "Singer-Songwriter",
          "Guitar",
          "British",
          "Grammy",
        ],
      },
      {
        objective: "Lady Gaga",
        taboos: [
          "Born This Way",
          "Poker Face",
          "Little Monsters",
          "Chromatica",
          "Joanne",
          "Stefani Germanotta",
          "Oscar",
          "The Fame",
          "Mother Monster",
          "Enigma",
        ],
      },
    ],
  },
  {
    category: "TV Shows",
    cards: [
      {
        objective: "Friends",
        taboos: [
          "Central Perk",
          "Rachel Green",
          "Ross Geller",
          "Monica Geller",
          "Chandler Bing",
          "Phoebe Buffay",
          "Joey Tribbiani",
          "Sitcom",
          "New York",
          "The One with the",
        ],
      },
      {
        objective: "Game of Thrones",
        taboos: [
          "Westeros",
          "Winterfell",
          "Dragons",
          "Starks",
          "Lannisters",
          "Daenerys Targaryen",
          "Jon Snow",
          "Fantasy",
          "HBO",
          "Iron Throne",
        ],
      },
      {
        objective: "Breaking Bad",
        taboos: [
          "Walter White",
          "Jesse Pinkman",
          "Heisenberg",
          "Meth",
          "Albuquerque",
          "AMC",
          "Bryan Cranston",
          "Chemistry",
          "Drug",
          "Blue Sky",
        ],
      },
      {
        objective: "The Simpsons",
        taboos: [
          "Homer Simpson",
          "Marge Simpson",
          "Bart Simpson",
          "Lisa Simpson",
          "Springfield",
          "Matt Groening",
          "Animated",
          "Family",
          "Yellow",
          "Fox",
        ],
      },
      {
        objective: "The Office",
        taboos: [
          "Dunder Mifflin",
          "Michael Scott",
          "Jim Halpert",
          "Pam Beesly",
          "Dwight Schrute",
          "Steve Carell",
          "Scranton",
          "Mockumentary",
          "Office",
          "NBC",
        ],
      },
      {
        objective: "Stranger Things",
        taboos: [
          "Upside Down",
          "Eleven",
          "Dungeons & Dragons",
          "Demogorgon",
          "Hawkins",
          "Netflix",
          "Mike Wheeler",
          "Sci-Fi",
          "Eggo",
          "Winona Ryder",
        ],
      },
      {
        objective: "The Walking Dead",
        taboos: [
          "Zombies",
          "Rick Grimes",
          "Survival",
          "AMC",
          "Daryl Dixon",
          "Apocalypse",
          "Georgia",
          "Post-Apocalyptic",
          "Negan",
          "Comic",
        ],
      },
      {
        objective: "Breaking Bad",
        taboos: [
          "Walter White",
          "Jesse Pinkman",
          "Heisenberg",
          "Meth",
          "Albuquerque",
          "AMC",
          "Bryan Cranston",
          "Chemistry",
          "Drug",
          "Blue Sky",
        ],
      },
      {
        objective: "The Crown",
        taboos: [
          "Queen Elizabeth II",
          "Royal Family",
          "Netflix",
          "British",
          "Monarchy",
          "Historical",
          "Claire Foy",
          "Olivia Colman",
          "Drama",
          "Golden Globe",
        ],
      },
      {
        objective: "Black Mirror",
        taboos: [
          "Technology",
          "Dystopian",
          "Anthology",
          "Charlie Brooker",
          "Netflix",
          "Futuristic",
          "Mirror",
          "Twilight Zone",
          "Satire",
          "Social Commentary",
        ],
      },
    ],
  },
];

export function getCategories(): string[] {
  return terms.map((t) => t.category);
}

export function getRandomCards(count: number, category?: string): Card[] {
  const source = category
    ? terms.find((t) => t.category === category)?.cards ?? []
    : terms.flatMap((t) => t.cards);
  const shuffled = [...source].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
