export type Card = {
  objective: string;
  taboos: string[];
};

export const terms = [
  {
    category: "Movies",
    cards: [
      {
        objective: "The Godfather",
        taboos: [
          "Mafia",
          "Don Corleone",
          "Marlon Brando",
          "New York",
          "Crime",
          "Family",
          "Vito",
          "Michael",
          "Godfather",
          "Offer",
        ],
      },
      {
        objective: "Star Wars",
        taboos: [
          "Jedi",
          "Darth Vader",
          "Luke Skywalker",
          "Lightsaber",
          "Force",
          "Galaxy",
          "Princess Leia",
          "Empire",
          "Han Solo",
          "Space",
        ],
      },
      {
        objective: "Jurassic Park",
        taboos: [
          "Dinosaurs",
          "T-Rex",
          "Steven Spielberg",
          "Island",
          "Adventure",
          "Prehistoric",
          "Velociraptor",
          "Fossils",
          "Park",
          "Jeff Goldblum",
        ],
      },
      {
        objective: "The Matrix",
        taboos: [
          "Neo",
          "Keanu Reeves",
          "Virtual Reality",
          "Red Pill",
          "Blue Pill",
          "Morpheus",
          "Cyberpunk",
          "Trinity",
          "Agent Smith",
          "Computer",
        ],
      },
      {
        objective: "Forrest Gump",
        taboos: [
          "Tom Hanks",
          "Vietnam War",
          "Life is like a box of chocolates",
          "Jenny",
          "Run Forrest, run",
          "Bubba",
          "Shrimp",
          "Alabama",
          "Ping Pong",
          "Lieutenant Dan",
        ],
      },
      {
        objective: "Inception",
        taboos: [
          "Dreams",
          "Leonardo DiCaprio",
          "Christopher Nolan",
          "Reality",
          "Cobb",
          "Dream within a dream",
          "Architecture",
          "Mind",
          "Heist",
          "Top",
        ],
      },
      {
        objective: "The Shawshank Redemption",
        taboos: [
          "Prison",
          "Stephen King",
          "Andy Dufresne",
          "Red",
          "Hope",
          "Escape",
          "Redemption",
          "Morgan Freeman",
          "Innocence",
          "Warden",
        ],
      },
      {
        objective: "The Lord of the Rings: The Fellowship of the Ring",
        taboos: [
          "Middle-earth",
          "Frodo Baggins",
          "Gandalf",
          "Ring",
          "Hobbits",
          "Fantasy",
          "Sauron",
          "Quest",
          "Samwise Gamgee",
          "J.R.R. Tolkien",
        ],
      },
      {
        objective: "The Dark Knight",
        taboos: [
          "Batman",
          "Joker",
          "Gotham",
          "Heath Ledger",
          "Christian Bale",
          "Superhero",
          "Crime",
          "Harvey Dent",
          "Christopher Nolan",
          "Gotham City",
        ],
      },
      {
        objective: "Pulp Fiction",
        taboos: [
          "Quentin Tarantino",
          "Vincent Vega",
          "Mia Wallace",
          "Samuel L. Jackson",
          "John Travolta",
          "Crime",
          "Violence",
          "Royale with Cheese",
          "Uma Thurman",
          "Hitmen",
        ],
      },
    ],
  },
  {
    category: "Pop Singers",
    cards: [
      {
        objective: "Michael Jackson",
        taboos: [
          "Thriller",
          "King of Pop",
          "Moonwalk",
          "Billie Jean",
          "Beat It",
          "Jackson 5",
          "Pop",
          "Dance",
          "Legend",
          "Glove",
        ],
      },
      {
        objective: "Beyoncé",
        taboos: [
          "Destiny's Child",
          "Queen Bey",
          "Formation",
          "Lemonade",
          "Single Ladies",
          "Jay-Z",
          "Sasha Fierce",
          "Formation World Tour",
          "Coachella",
          "Empowerment",
        ],
      },
      {
        objective: "Elvis Presley",
        taboos: [
          "The King",
          "Graceland",
          "Rock and Roll",
          "Blue Suede Shoes",
          "Hound Dog",
          "Jailhouse Rock",
          "Memphis",
          "Guitar",
          "Pelvis",
          "Heartbreak Hotel",
        ],
      },
      {
        objective: "Madonna",
        taboos: [
          "Material Girl",
          "Like a Virgin",
          "Queen of Pop",
          "Vogue",
          "Ray of Light",
          "Rebel Heart",
          "Ciccone",
          "Pioneer",
          "Icon",
          "Like a Prayer",
        ],
      },
      {
        objective: "Justin Bieber",
        taboos: [
          "Beliebers",
          "Purpose",
          "Baby",
          "Canada",
          "Scooter Braun",
          "Hailey Baldwin",
          "Sorry",
          "Yummy",
          "Purpose World Tour",
          "Love Yourself",
        ],
      },
      {
        objective: "Adele",
        taboos: [
          "Hello",
          "Someone Like You",
          "Rolling in the Deep",
          "21",
          "Grammy",
          "Skyfall",
          "Chasing Pavements",
          "British",
          "Soulful",
          "Voice",
        ],
      },
      {
        objective: "Taylor Swift",
        taboos: [
          "Swifties",
          "Red",
          "Fearless",
          "1989",
          "Shake It Off",
          "Blank Space",
          "Lover",
          "Country",
          "Singer-Songwriter",
          "Pop",
        ],
      },
      {
        objective: "Rihanna",
        taboos: [
          "Umbrella",
          "Rude Boy",
          "Diamonds",
          "Work",
          "Barbados",
          "Anti",
          "Fenty Beauty",
          "Fashion",
          "Savage X Fenty",
          "Navy",
        ],
      },
      {
        objective: "Ed Sheeran",
        taboos: [
          "Shape of You",
          "Thinking Out Loud",
          "Castle on the Hill",
          "The A Team",
          "Divide",
          "Ginger",
          "Singer-Songwriter",
          "Guitar",
          "British",
          "Grammy",
        ],
      },
      {
        objective: "Lady Gaga",
        taboos: [
          "Born This Way",
          "Poker Face",
          "Little Monsters",
          "Chromatica",
          "Joanne",
          "Stefani Germanotta",
          "Oscar",
          "The Fame",
          "Mother Monster",
          "Enigma",
        ],
      },
    ],
  },
  {
    category: "TV Shows",
    cards: [
      {
        objective: "Friends",
        taboos: [
          "Central Perk",
          "Rachel Green",
          "Ross Geller",
          "Monica Geller",
          "Chandler Bing",
          "Phoebe Buffay",
          "Joey Tribbiani",
          "Sitcom",
          "New York",
          "The One with the",
        ],
      },
      {
        objective: "Game of Thrones",
        taboos: [
          "Westeros",
          "Winterfell",
          "Dragons",
          "Starks",
          "Lannisters",
          "Daenerys Targaryen",
          "Jon Snow",
          "Fantasy",
          "HBO",
          "Iron Throne",
        ],
      },
      {
        objective: "Breaking Bad",
        taboos: [
          "Walter White",
          "Jesse Pinkman",
          "Heisenberg",
          "Meth",
          "Albuquerque",
          "AMC",
          "Bryan Cranston",
          "Chemistry",
          "Drug",
          "Blue Sky",
        ],
      },
      {
        objective: "The Simpsons",
        taboos: [
          "Homer Simpson",
          "Marge Simpson",
          "Bart Simpson",
          "Lisa Simpson",
          "Springfield",
          "Matt Groening",
          "Animated",
          "Family",
          "Yellow",
          "Fox",
        ],
      },
      {
        objective: "The Office",
        taboos: [
          "Dunder Mifflin",
          "Michael Scott",
          "Jim Halpert",
          "Pam Beesly",
          "Dwight Schrute",
          "Steve Carell",
          "Scranton",
          "Mockumentary",
          "Office",
          "NBC",
        ],
      },
      {
        objective: "Stranger Things",
        taboos: [
          "Upside Down",
          "Eleven",
          "Dungeons & Dragons",
          "Demogorgon",
          "Hawkins",
          "Netflix",
          "Mike Wheeler",
          "Sci-Fi",
          "Eggo",
          "Winona Ryder",
        ],
      },
      {
        objective: "The Walking Dead",
        taboos: [
          "Zombies",
          "Rick Grimes",
          "Survival",
          "AMC",
          "Daryl Dixon",
          "Apocalypse",
          "Georgia",
          "Post-Apocalyptic",
          "Negan",
          "Comic",
        ],
      },
      {
        objective: "Breaking Bad",
        taboos: [
          "Walter White",
          "Jesse Pinkman",
          "Heisenberg",
          "Meth",
          "Albuquerque",
          "AMC",
          "Bryan Cranston",
          "Chemistry",
          "Drug",
          "Blue Sky",
        ],
      },
      {
        objective: "The Crown",
        taboos: [
          "Queen Elizabeth II",
          "Royal Family",
          "Netflix",
          "British",
          "Monarchy",
          "Historical",
          "Claire Foy",
          "Olivia Colman",
          "Drama",
          "Golden Globe",
        ],
      },
      {
        objective: "Black Mirror",
        taboos: [
          "Technology",
          "Dystopian",
          "Anthology",
          "Charlie Brooker",
          "Netflix",
          "Futuristic",
          "Mirror",
          "Twilight Zone",
          "Satire",
          "Social Commentary",
        ],
      },
    ],
  },
];

export const terms2 = [
  {
    objective: "Milano Cortina",
    category: "Sports",
    taboos: [
      { word: "Olympics", relevancyScore: 10 },
      { word: "Italy", relevancyScore: 9 },
      { word: "Winter", relevancyScore: 8 },
      { word: "Paralympics", relevancyScore: 7 },
      { word: "skiing", relevancyScore: 6 },
      { word: "snow", relevancyScore: 5 },
      { word: "2026", relevancyScore: 4 },
      { word: "Alps", relevancyScore: 3 },
    ],
  },
  {
    objective: "Harry Styles",
    category: "Pop Singers",
    taboos: [
      { word: "One Direction", relevancyScore: 10 },
      { word: "As It Was", relevancyScore: 9 },
      { word: "boy band", relevancyScore: 8 },
      { word: "British", relevancyScore: 7 },
      { word: "singer", relevancyScore: 6 },
      { word: "album", relevancyScore: 5 },
      { word: "Grammy", relevancyScore: 4 },
      { word: "concert", relevancyScore: 3 },
    ],
  },
  {
    objective: "Formula 1",
    category: "Sports",
    taboos: [
      { word: "racing", relevancyScore: 10 },
      { word: "cars", relevancyScore: 9 },
      { word: "Grand Prix", relevancyScore: 8 },
      { word: "drivers", relevancyScore: 7 },
      { word: "track", relevancyScore: 6 },
      { word: "Ferrari", relevancyScore: 5 },
      { word: "pit stop", relevancyScore: 4 },
      { word: "speed", relevancyScore: 3 },
    ],
  },
  {
    objective: "Super Bowl",
    category: "Sports",
    taboos: [
      { word: "football", relevancyScore: 10 },
      { word: "NFL", relevancyScore: 9 },
      { word: "halftime", relevancyScore: 8 },
      { word: "championship", relevancyScore: 7 },
      { word: "touchdown", relevancyScore: 6 },
      { word: "commercials", relevancyScore: 5 },
      { word: "Sunday", relevancyScore: 4 },
      { word: "stadium", relevancyScore: 3 },
    ],
  },
  {
    objective: "Outlander",
    category: "TV Shows",
    taboos: [
      { word: "time travel", relevancyScore: 10 },
      { word: "Scotland", relevancyScore: 9 },
      { word: "Claire", relevancyScore: 8 },
      { word: "Jamie", relevancyScore: 7 },
      { word: "Starz", relevancyScore: 6 },
      { word: "romance", relevancyScore: 5 },
      { word: "history", relevancyScore: 4 },
      { word: "series", relevancyScore: 3 },
    ],
  },
  {
    objective: "War Machine",
    category: "Movies",
    taboos: [
      { word: "Netflix", relevancyScore: 10 },
      { word: "aliens", relevancyScore: 9 },
      { word: "soldiers", relevancyScore: 8 },
      { word: "sci-fi", relevancyScore: 7 },
      { word: "battle", relevancyScore: 6 },
      { word: "army", relevancyScore: 5 },
      { word: "action", relevancyScore: 4 },
      { word: "invasion", relevancyScore: 3 },
    ],
  },
  {
    objective: "Taylor Swift",
    category: "Pop Singers",
    taboos: [
      { word: "Swifties", relevancyScore: 10 },
      { word: "Eras Tour", relevancyScore: 9 },
      { word: "pop", relevancyScore: 8 },
      { word: "Grammy", relevancyScore: 7 },
      { word: "singer", relevancyScore: 6 },
      { word: "songwriter", relevancyScore: 5 },
      { word: "breakup songs", relevancyScore: 4 },
      { word: "concert", relevancyScore: 3 },
    ],
  },
  {
    objective: "Travis Scott",
    category: "Pop Singers",
    taboos: [
      { word: "rapper", relevancyScore: 10 },
      { word: "Astroworld", relevancyScore: 9 },
      { word: "Houston", relevancyScore: 8 },
      { word: "hip hop", relevancyScore: 7 },
      { word: "concert", relevancyScore: 6 },
      { word: "album", relevancyScore: 5 },
      { word: "festival", relevancyScore: 4 },
      { word: "stage", relevancyScore: 3 },
    ],
  },
  {
    objective: "Madison Square Garden",
    category: "Places",
    taboos: [
      { word: "New York", relevancyScore: 10 },
      { word: "arena", relevancyScore: 9 },
      { word: "Knicks", relevancyScore: 8 },
      { word: "Rangers", relevancyScore: 7 },
      { word: "concerts", relevancyScore: 6 },
      { word: "Manhattan", relevancyScore: 5 },
      { word: "stadium", relevancyScore: 4 },
      { word: "venue", relevancyScore: 3 },
    ],
  },
  {
    objective: "March Madness",
    category: "Sports",
    taboos: [
      { word: "basketball", relevancyScore: 10 },
      { word: "NCAA", relevancyScore: 9 },
      { word: "tournament", relevancyScore: 8 },
      { word: "bracket", relevancyScore: 7 },
      { word: "college", relevancyScore: 6 },
      { word: "Final Four", relevancyScore: 5 },
      { word: "upset", relevancyScore: 4 },
      { word: "teams", relevancyScore: 3 },
    ],
  },
  {
    objective: "Star Wars",
    category: "1970s",
    taboos: [
      { word: "Jedi", relevancyScore: 10 },
      { word: "lightsaber", relevancyScore: 9 },
      { word: "Luke", relevancyScore: 8 },
      { word: "Darth Vader", relevancyScore: 7 },
      { word: "space", relevancyScore: 6 },
      { word: "force", relevancyScore: 5 },
      { word: "galaxy", relevancyScore: 4 },
      { word: "sci-fi", relevancyScore: 3 },
    ],
  },
  {
    objective: "The Godfather",
    category: "1970s",
    taboos: [
      { word: "mafia", relevancyScore: 10 },
      { word: "Corleone", relevancyScore: 9 },
      { word: "mob", relevancyScore: 8 },
      { word: "Marlon Brando", relevancyScore: 7 },
      { word: "crime family", relevancyScore: 6 },
      { word: "don", relevancyScore: 5 },
      { word: "Italian", relevancyScore: 4 },
      { word: "movie", relevancyScore: 3 },
    ],
  },
  {
    objective: "Saturday Night Fever",
    category: "1970s",
    taboos: [
      { word: "disco", relevancyScore: 10 },
      { word: "John Travolta", relevancyScore: 9 },
      { word: "dancing", relevancyScore: 8 },
      { word: "Bee Gees", relevancyScore: 7 },
      { word: "dance floor", relevancyScore: 6 },
      { word: "white suit", relevancyScore: 5 },
      { word: "nightclub", relevancyScore: 4 },
      { word: "Brooklyn", relevancyScore: 3 },
    ],
  },
  {
    objective: "Jaws",
    category: "1970s",
    taboos: [
      { word: "shark", relevancyScore: 10 },
      { word: "beach", relevancyScore: 9 },
      { word: "ocean", relevancyScore: 8 },
      { word: "Steven Spielberg", relevancyScore: 7 },
      { word: "boat", relevancyScore: 6 },
      { word: "attack", relevancyScore: 5 },
      { word: "summer", relevancyScore: 4 },
      { word: "thriller", relevancyScore: 3 },
    ],
  },
  {
    objective: "Rocky",
    category: "1970s",
    taboos: [
      { word: "boxing", relevancyScore: 10 },
      { word: "Sylvester Stallone", relevancyScore: 9 },
      { word: "Philadelphia", relevancyScore: 8 },
      { word: "fight", relevancyScore: 7 },
      { word: "champion", relevancyScore: 6 },
      { word: "training", relevancyScore: 5 },
      { word: "steps", relevancyScore: 4 },
      { word: "underdog", relevancyScore: 3 },
    ],
  },
  {
    objective: "Muhammad Ali",
    category: "1970s",
    taboos: [
      { word: "boxing", relevancyScore: 10 },
      { word: "champion", relevancyScore: 9 },
      { word: "ring", relevancyScore: 8 },
      { word: "Joe Frazier", relevancyScore: 7 },
      { word: "fight", relevancyScore: 6 },
      { word: "heavyweight", relevancyScore: 5 },
      { word: "Olympics", relevancyScore: 4 },
      { word: "knockout", relevancyScore: 3 },
    ],
  },
  {
    objective: "ABBA",
    category: "1970s",
    taboos: [
      { word: "Swedish", relevancyScore: 10 },
      { word: "Dancing Queen", relevancyScore: 9 },
      { word: "pop group", relevancyScore: 8 },
      { word: "Mamma Mia", relevancyScore: 7 },
      { word: "Eurovision", relevancyScore: 6 },
      { word: "music", relevancyScore: 5 },
      { word: "band", relevancyScore: 4 },
      { word: "70s", relevancyScore: 3 },
    ],
  },
  {
    objective: "Charlie’s Angels",
    category: "1970s",
    taboos: [
      { word: "detectives", relevancyScore: 10 },
      { word: "Farrah Fawcett", relevancyScore: 9 },
      { word: "crime", relevancyScore: 8 },
      { word: "investigation", relevancyScore: 7 },
      { word: "television", relevancyScore: 6 },
      { word: "boss", relevancyScore: 5 },
      { word: "agency", relevancyScore: 4 },
      { word: "1970s", relevancyScore: 3 },
    ],
  },
  {
    objective: "Disco",
    category: "1970s",
    taboos: [
      { word: "dance", relevancyScore: 10 },
      { word: "nightclub", relevancyScore: 9 },
      { word: "Bee Gees", relevancyScore: 8 },
      { word: "music", relevancyScore: 7 },
      { word: "mirror ball", relevancyScore: 6 },
      { word: "party", relevancyScore: 5 },
      { word: "DJ", relevancyScore: 4 },
      { word: "1970s", relevancyScore: 3 },
    ],
  },
  {
    objective: "Watergate",
    category: "1970s",
    taboos: [
      { word: "Nixon", relevancyScore: 10 },
      { word: "scandal", relevancyScore: 9 },
      { word: "president", relevancyScore: 8 },
      { word: "break-in", relevancyScore: 7 },
      { word: "White House", relevancyScore: 6 },
      { word: "resignation", relevancyScore: 5 },
      { word: "politics", relevancyScore: 4 },
      { word: "1970s", relevancyScore: 3 },
    ],
  },

  {
    objective: "Back to the Future",
    category: "1980s",
    taboos: [
      { word: "time travel", relevancyScore: 10 },
      { word: "DeLorean", relevancyScore: 9 },
      { word: "Marty", relevancyScore: 8 },
      { word: "Doc Brown", relevancyScore: 7 },
      { word: "1985", relevancyScore: 6 },
      { word: "clock tower", relevancyScore: 5 },
      { word: "lightning", relevancyScore: 4 },
      { word: "science fiction", relevancyScore: 3 },
    ],
  },
  {
    objective: "The Breakfast Club",
    category: "1980s",
    taboos: [
      { word: "detention", relevancyScore: 10 },
      { word: "high school", relevancyScore: 9 },
      { word: "teenagers", relevancyScore: 8 },
      { word: "John Hughes", relevancyScore: 7 },
      { word: "Saturday", relevancyScore: 6 },
      { word: "students", relevancyScore: 5 },
      { word: "principal", relevancyScore: 4 },
      { word: "1980s", relevancyScore: 3 },
    ],
  },
  {
    objective: "Ghostbusters",
    category: "1980s",
    taboos: [
      { word: "ghost", relevancyScore: 10 },
      { word: "proton pack", relevancyScore: 9 },
      { word: "slime", relevancyScore: 8 },
      { word: "Bill Murray", relevancyScore: 7 },
      { word: "paranormal", relevancyScore: 6 },
      { word: "trap", relevancyScore: 5 },
      { word: "New York", relevancyScore: 4 },
      { word: "comedy", relevancyScore: 3 },
    ],
  },
  {
    objective: "E.T.",
    category: "1980s",
    taboos: [
      { word: "alien", relevancyScore: 10 },
      { word: "phone home", relevancyScore: 9 },
      { word: "spaceship", relevancyScore: 8 },
      { word: "bike", relevancyScore: 7 },
      { word: "Steven Spielberg", relevancyScore: 6 },
      { word: "friendship", relevancyScore: 5 },
      { word: "kids", relevancyScore: 4 },
      { word: "1980s", relevancyScore: 3 },
    ],
  },
  {
    objective: "Michael Jackson",
    category: "1980s",
    taboos: [
      { word: "Thriller", relevancyScore: 10 },
      { word: "moonwalk", relevancyScore: 9 },
      { word: "pop", relevancyScore: 8 },
      { word: "glove", relevancyScore: 7 },
      { word: "singer", relevancyScore: 6 },
      { word: "dance", relevancyScore: 5 },
      { word: "music video", relevancyScore: 4 },
      { word: "1980s", relevancyScore: 3 },
    ],
  },
  {
    objective: "Madonna",
    category: "1980s",
    taboos: [
      { word: "Like a Virgin", relevancyScore: 10 },
      { word: "pop star", relevancyScore: 9 },
      { word: "Material Girl", relevancyScore: 8 },
      { word: "singer", relevancyScore: 7 },
      { word: "music", relevancyScore: 6 },
      { word: "fashion", relevancyScore: 5 },
      { word: "concert", relevancyScore: 4 },
      { word: "1980s", relevancyScore: 3 },
    ],
  },
  {
    objective: "Nintendo",
    category: "1980s",
    taboos: [
      { word: "video game", relevancyScore: 10 },
      { word: "console", relevancyScore: 9 },
      { word: "Mario", relevancyScore: 8 },
      { word: "controller", relevancyScore: 7 },
      { word: "NES", relevancyScore: 6 },
      { word: "gaming", relevancyScore: 5 },
      { word: "cartridge", relevancyScore: 4 },
      { word: "1980s", relevancyScore: 3 },
    ],
  },
  {
    objective: "Berlin Wall",
    category: "1980s",
    taboos: [
      { word: "Germany", relevancyScore: 10 },
      { word: "Cold War", relevancyScore: 9 },
      { word: "East", relevancyScore: 8 },
      { word: "West", relevancyScore: 7 },
      { word: "barrier", relevancyScore: 6 },
      { word: "communism", relevancyScore: 5 },
      { word: "1989", relevancyScore: 4 },
      { word: "Europe", relevancyScore: 3 },
    ],
  },
  {
    objective: "Magic Johnson",
    category: "1980s",
    taboos: [
      { word: "basketball", relevancyScore: 10 },
      { word: "Lakers", relevancyScore: 9 },
      { word: "NBA", relevancyScore: 8 },
      { word: "point guard", relevancyScore: 7 },
      { word: "championship", relevancyScore: 6 },
      { word: "showtime", relevancyScore: 5 },
      { word: "Los Angeles", relevancyScore: 4 },
      { word: "1980s", relevancyScore: 3 },
    ],
  },

  {
    objective: "Titanic",
    category: "1990s",
    taboos: [
      { word: "ship", relevancyScore: 10 },
      { word: "iceberg", relevancyScore: 9 },
      { word: "Leonardo DiCaprio", relevancyScore: 8 },
      { word: "Kate Winslet", relevancyScore: 7 },
      { word: "sinking", relevancyScore: 6 },
      { word: "romance", relevancyScore: 5 },
      { word: "ocean", relevancyScore: 4 },
      { word: "1997", relevancyScore: 3 },
    ],
  },
  {
    objective: "Jurassic Park",
    category: "1990s",
    taboos: [
      { word: "dinosaurs", relevancyScore: 10 },
      { word: "T-rex", relevancyScore: 9 },
      { word: "island", relevancyScore: 8 },
      { word: "Steven Spielberg", relevancyScore: 7 },
      { word: "park", relevancyScore: 6 },
      { word: "science", relevancyScore: 5 },
      { word: "genetics", relevancyScore: 4 },
      { word: "1990s", relevancyScore: 3 },
    ],
  },
  {
    objective: "The Matrix",
    category: "1990s",
    taboos: [
      { word: "Neo", relevancyScore: 10 },
      { word: "bullet time", relevancyScore: 9 },
      { word: "Keanu Reeves", relevancyScore: 8 },
      { word: "simulation", relevancyScore: 7 },
      { word: "red pill", relevancyScore: 6 },
      { word: "sci-fi", relevancyScore: 5 },
      { word: "computers", relevancyScore: 4 },
      { word: "1999", relevancyScore: 3 },
    ],
  },
  {
    objective: "Friends",
    category: "1990s",
    taboos: [
      { word: "sitcom", relevancyScore: 10 },
      { word: "Rachel", relevancyScore: 9 },
      { word: "Central Perk", relevancyScore: 8 },
      { word: "New York", relevancyScore: 7 },
      { word: "six friends", relevancyScore: 6 },
      { word: "Ross", relevancyScore: 5 },
      { word: "coffee shop", relevancyScore: 4 },
      { word: "1990s", relevancyScore: 3 },
    ],
  },
  {
    objective: "Seinfeld",
    category: "1990s",
    taboos: [
      { word: "sitcom", relevancyScore: 10 },
      { word: "Jerry", relevancyScore: 9 },
      { word: "New York", relevancyScore: 8 },
      { word: "nothing", relevancyScore: 7 },
      { word: "George", relevancyScore: 6 },
      { word: "Elaine", relevancyScore: 5 },
      { word: "Kramer", relevancyScore: 4 },
      { word: "1990s", relevancyScore: 3 },
    ],
  },
  {
    objective: "Spice Girls",
    category: "1990s",
    taboos: [
      { word: "girl group", relevancyScore: 10 },
      { word: "Wannabe", relevancyScore: 9 },
      { word: "British", relevancyScore: 8 },
      { word: "Girl Power", relevancyScore: 7 },
      { word: "pop", relevancyScore: 6 },
      { word: "five members", relevancyScore: 5 },
      { word: "music", relevancyScore: 4 },
      { word: "1990s", relevancyScore: 3 },
    ],
  },
  {
    objective: "Nirvana",
    category: "1990s",
    taboos: [
      { word: "grunge", relevancyScore: 10 },
      { word: "Kurt Cobain", relevancyScore: 9 },
      { word: "Smells Like Teen Spirit", relevancyScore: 8 },
      { word: "Seattle", relevancyScore: 7 },
      { word: "rock band", relevancyScore: 6 },
      { word: "guitar", relevancyScore: 5 },
      { word: "1990s", relevancyScore: 4 },
      { word: "music", relevancyScore: 3 },
    ],
  },
  {
    objective: "PlayStation",
    category: "1990s",
    taboos: [
      { word: "Sony", relevancyScore: 10 },
      { word: "video game", relevancyScore: 9 },
      { word: "console", relevancyScore: 8 },
      { word: "controller", relevancyScore: 7 },
      { word: "gaming", relevancyScore: 6 },
      { word: "CD", relevancyScore: 5 },
      { word: "1990s", relevancyScore: 4 },
      { word: "games", relevancyScore: 3 },
    ],
  },
  {
    objective: "Michael Jordan",
    category: "1990s",
    taboos: [
      { word: "basketball", relevancyScore: 10 },
      { word: "Chicago Bulls", relevancyScore: 9 },
      { word: "NBA", relevancyScore: 8 },
      { word: "slam dunk", relevancyScore: 7 },
      { word: "championship", relevancyScore: 6 },
      { word: "Air Jordan", relevancyScore: 5 },
      { word: "23", relevancyScore: 4 },
      { word: "1990s", relevancyScore: 3 },
    ],
  },
  {
    objective: "Y2K",
    category: "1990s",
    taboos: [
      { word: "2000", relevancyScore: 10 },
      { word: "computers", relevancyScore: 9 },
      { word: "millennium", relevancyScore: 8 },
      { word: "bug", relevancyScore: 7 },
      { word: "technology", relevancyScore: 6 },
      { word: "calendar", relevancyScore: 5 },
      { word: "panic", relevancyScore: 4 },
      { word: "1999", relevancyScore: 3 },
    ],
  },
];

export function getCategories(): string[] {
  return terms.map((t) => t.category);
}

export function getRandomCards(count: number, category?: string): Card[] {
  const source = category
    ? (terms.find((t) => t.category === category)?.cards ?? [])
    : terms.flatMap((t) => t.cards);
  const shuffled = [...source].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
