import "dotenv/config";
import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import * as schema from "../lib/db/schema";
import type { WordCard } from "../lib/cards";

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql, { schema });

const cards: WordCard[] = [
  // ── Food & Drink ────────────────────────────────────────────────────────────
  {
    objective: "Sushi",
    category: "Food & Drink",
    taboos: [
      { word: "Japan", relevancyScore: 10 },
      { word: "raw fish", relevancyScore: 9 },
      { word: "rice", relevancyScore: 8 },
      { word: "seaweed", relevancyScore: 7 },
      { word: "chopsticks", relevancyScore: 6 },
      { word: "restaurant", relevancyScore: 5 },
      { word: "roll", relevancyScore: 4 },
      { word: "wasabi", relevancyScore: 3 },
    ],
  },
  {
    objective: "Pizza",
    category: "Food & Drink",
    taboos: [
      { word: "Italy", relevancyScore: 10 },
      { word: "cheese", relevancyScore: 9 },
      { word: "dough", relevancyScore: 8 },
      { word: "tomato sauce", relevancyScore: 7 },
      { word: "pepperoni", relevancyScore: 6 },
      { word: "oven", relevancyScore: 5 },
      { word: "slice", relevancyScore: 4 },
      { word: "delivery", relevancyScore: 3 },
    ],
  },
  {
    objective: "Avocado Toast",
    category: "Food & Drink",
    taboos: [
      { word: "brunch", relevancyScore: 10 },
      { word: "millennial", relevancyScore: 9 },
      { word: "avocado", relevancyScore: 8 },
      { word: "bread", relevancyScore: 7 },
      { word: "trendy", relevancyScore: 6 },
      { word: "cafe", relevancyScore: 5 },
      { word: "Instagram", relevancyScore: 4 },
      { word: "egg", relevancyScore: 3 },
    ],
  },
  {
    objective: "Espresso",
    category: "Food & Drink",
    taboos: [
      { word: "coffee", relevancyScore: 10 },
      { word: "Italy", relevancyScore: 9 },
      { word: "caffeine", relevancyScore: 8 },
      { word: "shot", relevancyScore: 7 },
      { word: "machine", relevancyScore: 6 },
      { word: "strong", relevancyScore: 5 },
      { word: "morning", relevancyScore: 4 },
      { word: "cup", relevancyScore: 3 },
    ],
  },
  {
    objective: "Ramen",
    category: "Food & Drink",
    taboos: [
      { word: "Japan", relevancyScore: 10 },
      { word: "noodles", relevancyScore: 9 },
      { word: "broth", relevancyScore: 8 },
      { word: "bowl", relevancyScore: 7 },
      { word: "pork", relevancyScore: 6 },
      { word: "egg", relevancyScore: 5 },
      { word: "soup", relevancyScore: 4 },
      { word: "chopsticks", relevancyScore: 3 },
    ],
  },
  {
    objective: "Taco",
    category: "Food & Drink",
    taboos: [
      { word: "Mexico", relevancyScore: 10 },
      { word: "tortilla", relevancyScore: 9 },
      { word: "salsa", relevancyScore: 8 },
      { word: "beef", relevancyScore: 7 },
      { word: "cheese", relevancyScore: 6 },
      { word: "Tuesday", relevancyScore: 5 },
      { word: "guacamole", relevancyScore: 4 },
      { word: "shell", relevancyScore: 3 },
    ],
  },
  {
    objective: "Cheeseburger",
    category: "Food & Drink",
    taboos: [
      { word: "McDonald's", relevancyScore: 10 },
      { word: "beef", relevancyScore: 9 },
      { word: "bun", relevancyScore: 8 },
      { word: "American", relevancyScore: 7 },
      { word: "grill", relevancyScore: 6 },
      { word: "fast food", relevancyScore: 5 },
      { word: "ketchup", relevancyScore: 4 },
      { word: "lettuce", relevancyScore: 3 },
    ],
  },
  {
    objective: "Croissant",
    category: "Food & Drink",
    taboos: [
      { word: "France", relevancyScore: 10 },
      { word: "pastry", relevancyScore: 9 },
      { word: "butter", relevancyScore: 8 },
      { word: "bakery", relevancyScore: 7 },
      { word: "flaky", relevancyScore: 6 },
      { word: "breakfast", relevancyScore: 5 },
      { word: "crescent", relevancyScore: 4 },
      { word: "café", relevancyScore: 3 },
    ],
  },
  {
    objective: "Margarita",
    category: "Food & Drink",
    taboos: [
      { word: "tequila", relevancyScore: 10 },
      { word: "cocktail", relevancyScore: 9 },
      { word: "lime", relevancyScore: 8 },
      { word: "salt rim", relevancyScore: 7 },
      { word: "Mexico", relevancyScore: 6 },
      { word: "drink", relevancyScore: 5 },
      { word: "blended", relevancyScore: 4 },
      { word: "glass", relevancyScore: 3 },
    ],
  },
  {
    objective: "Boba Tea",
    category: "Food & Drink",
    taboos: [
      { word: "Taiwan", relevancyScore: 10 },
      { word: "tapioca", relevancyScore: 9 },
      { word: "pearls", relevancyScore: 8 },
      { word: "milk tea", relevancyScore: 7 },
      { word: "straw", relevancyScore: 6 },
      { word: "trendy", relevancyScore: 5 },
      { word: "Asian", relevancyScore: 4 },
      { word: "drink", relevancyScore: 3 },
    ],
  },

  // ── Tech ────────────────────────────────────────────────────────────────────
  {
    objective: "iPhone",
    category: "Tech",
    taboos: [
      { word: "Apple", relevancyScore: 10 },
      { word: "smartphone", relevancyScore: 9 },
      { word: "Steve Jobs", relevancyScore: 8 },
      { word: "iOS", relevancyScore: 7 },
      { word: "touchscreen", relevancyScore: 6 },
      { word: "app", relevancyScore: 5 },
      { word: "camera", relevancyScore: 4 },
      { word: "silicon", relevancyScore: 3 },
    ],
  },
  {
    objective: "ChatGPT",
    category: "Tech",
    taboos: [
      { word: "AI", relevancyScore: 10 },
      { word: "OpenAI", relevancyScore: 9 },
      { word: "chatbot", relevancyScore: 8 },
      { word: "language model", relevancyScore: 7 },
      { word: "Sam Altman", relevancyScore: 6 },
      { word: "text", relevancyScore: 5 },
      { word: "conversation", relevancyScore: 4 },
      { word: "prompt", relevancyScore: 3 },
    ],
  },
  {
    objective: "TikTok",
    category: "Tech",
    taboos: [
      { word: "video", relevancyScore: 10 },
      { word: "viral", relevancyScore: 9 },
      { word: "China", relevancyScore: 8 },
      { word: "short-form", relevancyScore: 7 },
      { word: "dance", relevancyScore: 6 },
      { word: "ByteDance", relevancyScore: 5 },
      { word: "ban", relevancyScore: 4 },
      { word: "scrolling", relevancyScore: 3 },
    ],
  },
  {
    objective: "Tesla",
    category: "Tech",
    taboos: [
      { word: "electric", relevancyScore: 10 },
      { word: "Elon Musk", relevancyScore: 9 },
      { word: "car", relevancyScore: 8 },
      { word: "autopilot", relevancyScore: 7 },
      { word: "battery", relevancyScore: 6 },
      { word: "charging", relevancyScore: 5 },
      { word: "Model S", relevancyScore: 4 },
      { word: "silicon valley", relevancyScore: 3 },
    ],
  },
  {
    objective: "SpaceX",
    category: "Tech",
    taboos: [
      { word: "rocket", relevancyScore: 10 },
      { word: "Elon Musk", relevancyScore: 9 },
      { word: "Mars", relevancyScore: 8 },
      { word: "Falcon 9", relevancyScore: 7 },
      { word: "NASA", relevancyScore: 6 },
      { word: "launch", relevancyScore: 5 },
      { word: "space", relevancyScore: 4 },
      { word: "Starship", relevancyScore: 3 },
    ],
  },
  {
    objective: "Virtual Reality",
    category: "Tech",
    taboos: [
      { word: "headset", relevancyScore: 10 },
      { word: "Meta", relevancyScore: 9 },
      { word: "immersive", relevancyScore: 8 },
      { word: "gaming", relevancyScore: 7 },
      { word: "simulation", relevancyScore: 6 },
      { word: "goggles", relevancyScore: 5 },
      { word: "3D", relevancyScore: 4 },
      { word: "experience", relevancyScore: 3 },
    ],
  },
  {
    objective: "Bitcoin",
    category: "Tech",
    taboos: [
      { word: "cryptocurrency", relevancyScore: 10 },
      { word: "blockchain", relevancyScore: 9 },
      { word: "Satoshi", relevancyScore: 8 },
      { word: "wallet", relevancyScore: 7 },
      { word: "mining", relevancyScore: 6 },
      { word: "investment", relevancyScore: 5 },
      { word: "digital", relevancyScore: 4 },
      { word: "crash", relevancyScore: 3 },
    ],
  },
  {
    objective: "Airpods",
    category: "Tech",
    taboos: [
      { word: "Apple", relevancyScore: 10 },
      { word: "wireless", relevancyScore: 9 },
      { word: "earbuds", relevancyScore: 8 },
      { word: "Bluetooth", relevancyScore: 7 },
      { word: "music", relevancyScore: 6 },
      { word: "white", relevancyScore: 5 },
      { word: "charging case", relevancyScore: 4 },
      { word: "noise-canceling", relevancyScore: 3 },
    ],
  },

  // ── Movies (recent) ─────────────────────────────────────────────────────────
  {
    objective: "Barbie",
    category: "Movies",
    taboos: [
      { word: "Margot Robbie", relevancyScore: 10 },
      { word: "pink", relevancyScore: 9 },
      { word: "Greta Gerwig", relevancyScore: 8 },
      { word: "Ryan Gosling", relevancyScore: 7 },
      { word: "Mattel", relevancyScore: 6 },
      { word: "doll", relevancyScore: 5 },
      { word: "Kenough", relevancyScore: 4 },
      { word: "2023", relevancyScore: 3 },
    ],
  },
  {
    objective: "Oppenheimer",
    category: "Movies",
    taboos: [
      { word: "atomic bomb", relevancyScore: 10 },
      { word: "Cillian Murphy", relevancyScore: 9 },
      { word: "Christopher Nolan", relevancyScore: 8 },
      { word: "Manhattan Project", relevancyScore: 7 },
      { word: "nuclear", relevancyScore: 6 },
      { word: "World War II", relevancyScore: 5 },
      { word: "physicist", relevancyScore: 4 },
      { word: "2023", relevancyScore: 3 },
    ],
  },
  {
    objective: "Top Gun: Maverick",
    category: "Movies",
    taboos: [
      { word: "Tom Cruise", relevancyScore: 10 },
      { word: "fighter jets", relevancyScore: 9 },
      { word: "Navy", relevancyScore: 8 },
      { word: "sequel", relevancyScore: 7 },
      { word: "aviation", relevancyScore: 6 },
      { word: "Maverick", relevancyScore: 5 },
      { word: "Goose", relevancyScore: 4 },
      { word: "2022", relevancyScore: 3 },
    ],
  },
  {
    objective: "Everything Everywhere All at Once",
    category: "Movies",
    taboos: [
      { word: "multiverse", relevancyScore: 10 },
      { word: "Michelle Yeoh", relevancyScore: 9 },
      { word: "Oscar", relevancyScore: 8 },
      { word: "Daniels", relevancyScore: 7 },
      { word: "laundromat", relevancyScore: 6 },
      { word: "A24", relevancyScore: 5 },
      { word: "hot dog fingers", relevancyScore: 4 },
      { word: "2022", relevancyScore: 3 },
    ],
  },
  {
    objective: "Dune",
    category: "Movies",
    taboos: [
      { word: "spice", relevancyScore: 10 },
      { word: "desert", relevancyScore: 9 },
      { word: "Timothée Chalamet", relevancyScore: 8 },
      { word: "sandworm", relevancyScore: 7 },
      { word: "Denis Villeneuve", relevancyScore: 6 },
      { word: "sci-fi", relevancyScore: 5 },
      { word: "Arrakis", relevancyScore: 4 },
      { word: "Paul Atreides", relevancyScore: 3 },
    ],
  },

  // ── TV Shows (recent) ───────────────────────────────────────────────────────
  {
    objective: "The Bear",
    category: "TV Shows",
    taboos: [
      { word: "restaurant", relevancyScore: 10 },
      { word: "kitchen", relevancyScore: 9 },
      { word: "chef", relevancyScore: 8 },
      { word: "Chicago", relevancyScore: 7 },
      { word: "Carmy", relevancyScore: 6 },
      { word: "Hulu", relevancyScore: 5 },
      { word: "stress", relevancyScore: 4 },
      { word: "Emmy", relevancyScore: 3 },
    ],
  },
  {
    objective: "Succession",
    category: "TV Shows",
    taboos: [
      { word: "Roy family", relevancyScore: 10 },
      { word: "HBO", relevancyScore: 9 },
      { word: "media empire", relevancyScore: 8 },
      { word: "Logan Roy", relevancyScore: 7 },
      { word: "billionaire", relevancyScore: 6 },
      { word: "power", relevancyScore: 5 },
      { word: "satire", relevancyScore: 4 },
      { word: "Waystar", relevancyScore: 3 },
    ],
  },
  {
    objective: "The Last of Us",
    category: "TV Shows",
    taboos: [
      { word: "zombie", relevancyScore: 10 },
      { word: "Pedro Pascal", relevancyScore: 9 },
      { word: "HBO", relevancyScore: 8 },
      { word: "fungus", relevancyScore: 7 },
      { word: "post-apocalyptic", relevancyScore: 6 },
      { word: "video game", relevancyScore: 5 },
      { word: "Joel", relevancyScore: 4 },
      { word: "Ellie", relevancyScore: 3 },
    ],
  },
  {
    objective: "Squid Game",
    category: "TV Shows",
    taboos: [
      { word: "Korea", relevancyScore: 10 },
      { word: "survival", relevancyScore: 9 },
      { word: "Netflix", relevancyScore: 8 },
      { word: "green tracksuit", relevancyScore: 7 },
      { word: "children's games", relevancyScore: 6 },
      { word: "prize money", relevancyScore: 5 },
      { word: "Red Light Green Light", relevancyScore: 4 },
      { word: "doll", relevancyScore: 3 },
    ],
  },
  {
    objective: "House of the Dragon",
    category: "TV Shows",
    taboos: [
      { word: "Game of Thrones", relevancyScore: 10 },
      { word: "dragons", relevancyScore: 9 },
      { word: "HBO", relevancyScore: 8 },
      { word: "Targaryens", relevancyScore: 7 },
      { word: "prequel", relevancyScore: 6 },
      { word: "civil war", relevancyScore: 5 },
      { word: "Westeros", relevancyScore: 4 },
      { word: "fantasy", relevancyScore: 3 },
    ],
  },
  {
    objective: "White Lotus",
    category: "TV Shows",
    taboos: [
      { word: "resort", relevancyScore: 10 },
      { word: "HBO", relevancyScore: 9 },
      { word: "satire", relevancyScore: 8 },
      { word: "wealthy", relevancyScore: 7 },
      { word: "Hawaii", relevancyScore: 6 },
      { word: "murder mystery", relevancyScore: 5 },
      { word: "tourists", relevancyScore: 4 },
      { word: "drama", relevancyScore: 3 },
    ],
  },

  // ── Places ──────────────────────────────────────────────────────────────────
  {
    objective: "Times Square",
    category: "Places",
    taboos: [
      { word: "New York", relevancyScore: 10 },
      { word: "billboard", relevancyScore: 9 },
      { word: "New Year's Eve", relevancyScore: 8 },
      { word: "tourist", relevancyScore: 7 },
      { word: "Broadway", relevancyScore: 6 },
      { word: "neon signs", relevancyScore: 5 },
      { word: "Manhattan", relevancyScore: 4 },
      { word: "crowded", relevancyScore: 3 },
    ],
  },
  {
    objective: "Eiffel Tower",
    category: "Places",
    taboos: [
      { word: "Paris", relevancyScore: 10 },
      { word: "France", relevancyScore: 9 },
      { word: "iron", relevancyScore: 8 },
      { word: "landmark", relevancyScore: 7 },
      { word: "romantic", relevancyScore: 6 },
      { word: "Gustave", relevancyScore: 5 },
      { word: "tourist", relevancyScore: 4 },
      { word: "tall", relevancyScore: 3 },
    ],
  },
  {
    objective: "The Great Wall of China",
    category: "Places",
    taboos: [
      { word: "China", relevancyScore: 10 },
      { word: "ancient", relevancyScore: 9 },
      { word: "wall", relevancyScore: 8 },
      { word: "dynasty", relevancyScore: 7 },
      { word: "long", relevancyScore: 6 },
      { word: "soldiers", relevancyScore: 5 },
      { word: "landmark", relevancyScore: 4 },
      { word: "border", relevancyScore: 3 },
    ],
  },

  // ── Animals ─────────────────────────────────────────────────────────────────
  {
    objective: "Panda",
    category: "Animals",
    taboos: [
      { word: "China", relevancyScore: 10 },
      { word: "black and white", relevancyScore: 9 },
      { word: "bamboo", relevancyScore: 8 },
      { word: "bear", relevancyScore: 7 },
      { word: "endangered", relevancyScore: 6 },
      { word: "WWF", relevancyScore: 5 },
      { word: "cute", relevancyScore: 4 },
      { word: "zoo", relevancyScore: 3 },
    ],
  },
  {
    objective: "Flamingo",
    category: "Animals",
    taboos: [
      { word: "pink", relevancyScore: 10 },
      { word: "bird", relevancyScore: 9 },
      { word: "one leg", relevancyScore: 8 },
      { word: "Florida", relevancyScore: 7 },
      { word: "tropical", relevancyScore: 6 },
      { word: "wading", relevancyScore: 5 },
      { word: "flock", relevancyScore: 4 },
      { word: "beak", relevancyScore: 3 },
    ],
  },
  {
    objective: "Octopus",
    category: "Animals",
    taboos: [
      { word: "tentacles", relevancyScore: 10 },
      { word: "eight", relevancyScore: 9 },
      { word: "ocean", relevancyScore: 8 },
      { word: "ink", relevancyScore: 7 },
      { word: "suction cups", relevancyScore: 6 },
      { word: "camouflage", relevancyScore: 5 },
      { word: "squid", relevancyScore: 4 },
      { word: "arms", relevancyScore: 3 },
    ],
  },
  {
    objective: "Peacock",
    category: "Animals",
    taboos: [
      { word: "feathers", relevancyScore: 10 },
      { word: "tail", relevancyScore: 9 },
      { word: "colorful", relevancyScore: 8 },
      { word: "bird", relevancyScore: 7 },
      { word: "India", relevancyScore: 6 },
      { word: "display", relevancyScore: 5 },
      { word: "fan", relevancyScore: 4 },
      { word: "blue", relevancyScore: 3 },
    ],
  },
  {
    objective: "Sloth",
    category: "Animals",
    taboos: [
      { word: "slow", relevancyScore: 10 },
      { word: "tree", relevancyScore: 9 },
      { word: "hang", relevancyScore: 8 },
      { word: "South America", relevancyScore: 7 },
      { word: "claws", relevancyScore: 6 },
      { word: "rainforest", relevancyScore: 5 },
      { word: "lazy", relevancyScore: 4 },
      { word: "upside down", relevancyScore: 3 },
    ],
  },

  // ── Music ────────────────────────────────────────────────────────────────────
  {
    objective: "The Beatles",
    category: "Music",
    taboos: [
      { word: "Liverpool", relevancyScore: 10 },
      { word: "John Lennon", relevancyScore: 9 },
      { word: "Paul McCartney", relevancyScore: 8 },
      { word: "Abbey Road", relevancyScore: 7 },
      { word: "British Invasion", relevancyScore: 6 },
      { word: "Fab Four", relevancyScore: 5 },
      { word: "rock band", relevancyScore: 4 },
      { word: "1960s", relevancyScore: 3 },
    ],
  },
  {
    objective: "Kendrick Lamar",
    category: "Music",
    taboos: [
      { word: "rapper", relevancyScore: 10 },
      { word: "Compton", relevancyScore: 9 },
      { word: "DAMN.", relevancyScore: 8 },
      { word: "Not Like Us", relevancyScore: 7 },
      { word: "hip-hop", relevancyScore: 6 },
      { word: "Pulitzer Prize", relevancyScore: 5 },
      { word: "halftime show", relevancyScore: 4 },
      { word: "Grammy", relevancyScore: 3 },
    ],
  },
  {
    objective: "Bad Bunny",
    category: "Music",
    taboos: [
      { word: "reggaeton", relevancyScore: 10 },
      { word: "Puerto Rico", relevancyScore: 9 },
      { word: "Latin", relevancyScore: 8 },
      { word: "Spanish", relevancyScore: 7 },
      { word: "Benito", relevancyScore: 6 },
      { word: "trap", relevancyScore: 5 },
      { word: "tour", relevancyScore: 4 },
      { word: "urban", relevancyScore: 3 },
    ],
  },
  {
    objective: "Dua Lipa",
    category: "Music",
    taboos: [
      { word: "Levitating", relevancyScore: 10 },
      { word: "pop star", relevancyScore: 9 },
      { word: "British", relevancyScore: 8 },
      { word: "Future Nostalgia", relevancyScore: 7 },
      { word: "dance-pop", relevancyScore: 6 },
      { word: "model", relevancyScore: 5 },
      { word: "Albanian", relevancyScore: 4 },
      { word: "Grammy", relevancyScore: 3 },
    ],
  },
  {
    objective: "Coldplay",
    category: "Music",
    taboos: [
      { word: "Chris Martin", relevancyScore: 10 },
      { word: "Yellow", relevancyScore: 9 },
      { word: "British", relevancyScore: 8 },
      { word: "Fix You", relevancyScore: 7 },
      { word: "rock band", relevancyScore: 6 },
      { word: "colorful concerts", relevancyScore: 5 },
      { word: "stadium", relevancyScore: 4 },
      { word: "Beyoncé", relevancyScore: 3 },
    ],
  },

  // ── Fashion & Brands ─────────────────────────────────────────────────────────
  {
    objective: "Supreme",
    category: "Fashion & Brands",
    taboos: [
      { word: "red box", relevancyScore: 10 },
      { word: "skateboarding", relevancyScore: 9 },
      { word: "streetwear", relevancyScore: 8 },
      { word: "New York", relevancyScore: 7 },
      { word: "limited edition", relevancyScore: 6 },
      { word: "hype", relevancyScore: 5 },
      { word: "logo", relevancyScore: 4 },
      { word: "resale", relevancyScore: 3 },
    ],
  },
  {
    objective: "Louis Vuitton",
    category: "Fashion & Brands",
    taboos: [
      { word: "luxury", relevancyScore: 10 },
      { word: "France", relevancyScore: 9 },
      { word: "handbag", relevancyScore: 8 },
      { word: "monogram", relevancyScore: 7 },
      { word: "Paris", relevancyScore: 6 },
      { word: "fashion house", relevancyScore: 5 },
      { word: "LV", relevancyScore: 4 },
      { word: "leather", relevancyScore: 3 },
    ],
  },
  {
    objective: "Adidas",
    category: "Fashion & Brands",
    taboos: [
      { word: "three stripes", relevancyScore: 10 },
      { word: "Germany", relevancyScore: 9 },
      { word: "sportswear", relevancyScore: 8 },
      { word: "soccer", relevancyScore: 7 },
      { word: "sneakers", relevancyScore: 6 },
      { word: "Yeezy", relevancyScore: 5 },
      { word: "Originals", relevancyScore: 4 },
      { word: "logo", relevancyScore: 3 },
    ],
  },
  {
    objective: "Gucci",
    category: "Fashion & Brands",
    taboos: [
      { word: "Italy", relevancyScore: 10 },
      { word: "luxury", relevancyScore: 9 },
      { word: "GG logo", relevancyScore: 8 },
      { word: "fashion house", relevancyScore: 7 },
      { word: "Milan", relevancyScore: 6 },
      { word: "designer", relevancyScore: 5 },
      { word: "green red stripe", relevancyScore: 4 },
      { word: "bag", relevancyScore: 3 },
    ],
  },
  {
    objective: "Air Jordans",
    category: "Fashion & Brands",
    taboos: [
      { word: "Nike", relevancyScore: 10 },
      { word: "basketball", relevancyScore: 9 },
      { word: "Michael Jordan", relevancyScore: 8 },
      { word: "sneakers", relevancyScore: 7 },
      { word: "Chicago Bulls", relevancyScore: 6 },
      { word: "Jumpman", relevancyScore: 5 },
      { word: "collectible", relevancyScore: 4 },
      { word: "hype", relevancyScore: 3 },
    ],
  },

  // ── Science & Nature ─────────────────────────────────────────────────────────
  {
    objective: "Black Hole",
    category: "Science & Nature",
    taboos: [
      { word: "space", relevancyScore: 10 },
      { word: "gravity", relevancyScore: 9 },
      { word: "event horizon", relevancyScore: 8 },
      { word: "singularity", relevancyScore: 7 },
      { word: "Einstein", relevancyScore: 6 },
      { word: "galaxy", relevancyScore: 5 },
      { word: "telescope", relevancyScore: 4 },
      { word: "dark", relevancyScore: 3 },
    ],
  },
  {
    objective: "Solar Eclipse",
    category: "Science & Nature",
    taboos: [
      { word: "moon", relevancyScore: 10 },
      { word: "sun", relevancyScore: 9 },
      { word: "shadow", relevancyScore: 8 },
      { word: "totality", relevancyScore: 7 },
      { word: "glasses", relevancyScore: 6 },
      { word: "rare", relevancyScore: 5 },
      { word: "darkness", relevancyScore: 4 },
      { word: "orbit", relevancyScore: 3 },
    ],
  },
  {
    objective: "Aurora Borealis",
    category: "Science & Nature",
    taboos: [
      { word: "Northern Lights", relevancyScore: 10 },
      { word: "sky", relevancyScore: 9 },
      { word: "Norway", relevancyScore: 8 },
      { word: "green", relevancyScore: 7 },
      { word: "Arctic", relevancyScore: 6 },
      { word: "colorful", relevancyScore: 5 },
      { word: "Iceland", relevancyScore: 4 },
      { word: "night", relevancyScore: 3 },
    ],
  },
  {
    objective: "Tsunami",
    category: "Science & Nature",
    taboos: [
      { word: "wave", relevancyScore: 10 },
      { word: "ocean", relevancyScore: 9 },
      { word: "earthquake", relevancyScore: 8 },
      { word: "disaster", relevancyScore: 7 },
      { word: "flooding", relevancyScore: 6 },
      { word: "coastline", relevancyScore: 5 },
      { word: "Japan", relevancyScore: 4 },
      { word: "tall", relevancyScore: 3 },
    ],
  },
  {
    objective: "Volcano",
    category: "Science & Nature",
    taboos: [
      { word: "lava", relevancyScore: 10 },
      { word: "eruption", relevancyScore: 9 },
      { word: "magma", relevancyScore: 8 },
      { word: "mountain", relevancyScore: 7 },
      { word: "Hawaii", relevancyScore: 6 },
      { word: "ash", relevancyScore: 5 },
      { word: "crater", relevancyScore: 4 },
      { word: "hot", relevancyScore: 3 },
    ],
  },

  // ── Mythology & Folklore ─────────────────────────────────────────────────────
  {
    objective: "Unicorn",
    category: "Mythology & Folklore",
    taboos: [
      { word: "horn", relevancyScore: 10 },
      { word: "horse", relevancyScore: 9 },
      { word: "magical", relevancyScore: 8 },
      { word: "rainbow", relevancyScore: 7 },
      { word: "mythical", relevancyScore: 6 },
      { word: "sparkle", relevancyScore: 5 },
      { word: "fantasy", relevancyScore: 4 },
      { word: "glitter", relevancyScore: 3 },
    ],
  },
  {
    objective: "Mermaid",
    category: "Mythology & Folklore",
    taboos: [
      { word: "fish tail", relevancyScore: 10 },
      { word: "ocean", relevancyScore: 9 },
      { word: "swimming", relevancyScore: 8 },
      { word: "half human", relevancyScore: 7 },
      { word: "scales", relevancyScore: 6 },
      { word: "Ariel", relevancyScore: 5 },
      { word: "mythology", relevancyScore: 4 },
      { word: "Little Mermaid", relevancyScore: 3 },
    ],
  },
  {
    objective: "Medusa",
    category: "Mythology & Folklore",
    taboos: [
      { word: "snakes", relevancyScore: 10 },
      { word: "hair", relevancyScore: 9 },
      { word: "Greek mythology", relevancyScore: 8 },
      { word: "stone", relevancyScore: 7 },
      { word: "gorgon", relevancyScore: 6 },
      { word: "Perseus", relevancyScore: 5 },
      { word: "eyes", relevancyScore: 4 },
      { word: "Athena", relevancyScore: 3 },
    ],
  },
  {
    objective: "Thor",
    category: "Mythology & Folklore",
    taboos: [
      { word: "hammer", relevancyScore: 10 },
      { word: "Norse", relevancyScore: 9 },
      { word: "lightning", relevancyScore: 8 },
      { word: "Mjolnir", relevancyScore: 7 },
      { word: "god", relevancyScore: 6 },
      { word: "Viking", relevancyScore: 5 },
      { word: "Asgard", relevancyScore: 4 },
      { word: "Marvel", relevancyScore: 3 },
    ],
  },
  {
    objective: "Bigfoot",
    category: "Mythology & Folklore",
    taboos: [
      { word: "Sasquatch", relevancyScore: 10 },
      { word: "footprint", relevancyScore: 9 },
      { word: "forest", relevancyScore: 8 },
      { word: "hairy", relevancyScore: 7 },
      { word: "cryptid", relevancyScore: 6 },
      { word: "Pacific Northwest", relevancyScore: 5 },
      { word: "blurry photo", relevancyScore: 4 },
      { word: "tall", relevancyScore: 3 },
    ],
  },

  // ── Games & Hobbies ──────────────────────────────────────────────────────────
  {
    objective: "Chess",
    category: "Games & Hobbies",
    taboos: [
      { word: "king", relevancyScore: 10 },
      { word: "queen", relevancyScore: 9 },
      { word: "checkmate", relevancyScore: 8 },
      { word: "board game", relevancyScore: 7 },
      { word: "strategy", relevancyScore: 6 },
      { word: "pawns", relevancyScore: 5 },
      { word: "knight", relevancyScore: 4 },
      { word: "tournament", relevancyScore: 3 },
    ],
  },
  {
    objective: "Monopoly",
    category: "Games & Hobbies",
    taboos: [
      { word: "board game", relevancyScore: 10 },
      { word: "properties", relevancyScore: 9 },
      { word: "jail", relevancyScore: 8 },
      { word: "banker", relevancyScore: 7 },
      { word: "real estate", relevancyScore: 6 },
      { word: "dice", relevancyScore: 5 },
      { word: "Hasbro", relevancyScore: 4 },
      { word: "go", relevancyScore: 3 },
    ],
  },
  {
    objective: "Yoga",
    category: "Games & Hobbies",
    taboos: [
      { word: "meditation", relevancyScore: 10 },
      { word: "pose", relevancyScore: 9 },
      { word: "flexibility", relevancyScore: 8 },
      { word: "India", relevancyScore: 7 },
      { word: "mat", relevancyScore: 6 },
      { word: "wellness", relevancyScore: 5 },
      { word: "stretching", relevancyScore: 4 },
      { word: "namaste", relevancyScore: 3 },
    ],
  },
  {
    objective: "Skateboarding",
    category: "Games & Hobbies",
    taboos: [
      { word: "tricks", relevancyScore: 10 },
      { word: "halfpipe", relevancyScore: 9 },
      { word: "Tony Hawk", relevancyScore: 8 },
      { word: "board", relevancyScore: 7 },
      { word: "ollie", relevancyScore: 6 },
      { word: "ramp", relevancyScore: 5 },
      { word: "skate park", relevancyScore: 4 },
      { word: "wheels", relevancyScore: 3 },
    ],
  },
  {
    objective: "Karaoke",
    category: "Games & Hobbies",
    taboos: [
      { word: "singing", relevancyScore: 10 },
      { word: "microphone", relevancyScore: 9 },
      { word: "Japan", relevancyScore: 8 },
      { word: "bar", relevancyScore: 7 },
      { word: "lyrics", relevancyScore: 6 },
      { word: "screen", relevancyScore: 5 },
      { word: "duet", relevancyScore: 4 },
      { word: "crowd", relevancyScore: 3 },
    ],
  },

  // ── Holidays & Events ────────────────────────────────────────────────────────
  {
    objective: "Halloween",
    category: "Holidays & Events",
    taboos: [
      { word: "trick or treat", relevancyScore: 10 },
      { word: "costumes", relevancyScore: 9 },
      { word: "pumpkin", relevancyScore: 8 },
      { word: "October 31", relevancyScore: 7 },
      { word: "candy", relevancyScore: 6 },
      { word: "haunted", relevancyScore: 5 },
      { word: "witch", relevancyScore: 4 },
      { word: "spooky", relevancyScore: 3 },
    ],
  },
  {
    objective: "Christmas",
    category: "Holidays & Events",
    taboos: [
      { word: "Santa", relevancyScore: 10 },
      { word: "presents", relevancyScore: 9 },
      { word: "December 25", relevancyScore: 8 },
      { word: "tree", relevancyScore: 7 },
      { word: "reindeer", relevancyScore: 6 },
      { word: "holiday", relevancyScore: 5 },
      { word: "snow", relevancyScore: 4 },
      { word: "ornament", relevancyScore: 3 },
    ],
  },
  {
    objective: "Fourth of July",
    category: "Holidays & Events",
    taboos: [
      { word: "fireworks", relevancyScore: 10 },
      { word: "Independence Day", relevancyScore: 9 },
      { word: "America", relevancyScore: 8 },
      { word: "patriotic", relevancyScore: 7 },
      { word: "barbecue", relevancyScore: 6 },
      { word: "flag", relevancyScore: 5 },
      { word: "red white blue", relevancyScore: 4 },
      { word: "July", relevancyScore: 3 },
    ],
  },
  {
    objective: "Mardi Gras",
    category: "Holidays & Events",
    taboos: [
      { word: "New Orleans", relevancyScore: 10 },
      { word: "beads", relevancyScore: 9 },
      { word: "Fat Tuesday", relevancyScore: 8 },
      { word: "parade", relevancyScore: 7 },
      { word: "Louisiana", relevancyScore: 6 },
      { word: "carnival", relevancyScore: 5 },
      { word: "Bourbon Street", relevancyScore: 4 },
      { word: "purple gold green", relevancyScore: 3 },
    ],
  },
  {
    objective: "St. Patrick's Day",
    category: "Holidays & Events",
    taboos: [
      { word: "Ireland", relevancyScore: 10 },
      { word: "green", relevancyScore: 9 },
      { word: "shamrock", relevancyScore: 8 },
      { word: "leprechaun", relevancyScore: 7 },
      { word: "luck", relevancyScore: 6 },
      { word: "March 17", relevancyScore: 5 },
      { word: "beer", relevancyScore: 4 },
      { word: "clover", relevancyScore: 3 },
    ],
  },

  // ── Sports ──────────────────────────────────────────────────────────────────
  {
    objective: "Lionel Messi",
    category: "Sports",
    taboos: [
      { word: "soccer", relevancyScore: 10 },
      { word: "Argentina", relevancyScore: 9 },
      { word: "World Cup", relevancyScore: 8 },
      { word: "Barcelona", relevancyScore: 7 },
      { word: "Inter Miami", relevancyScore: 6 },
      { word: "GOAT", relevancyScore: 5 },
      { word: "Ballon d'Or", relevancyScore: 4 },
      { word: "dribble", relevancyScore: 3 },
    ],
  },
  {
    objective: "LeBron James",
    category: "Sports",
    taboos: [
      { word: "basketball", relevancyScore: 10 },
      { word: "Lakers", relevancyScore: 9 },
      { word: "NBA", relevancyScore: 8 },
      { word: "championship", relevancyScore: 7 },
      { word: "Cleveland", relevancyScore: 6 },
      { word: "King", relevancyScore: 5 },
      { word: "Miami Heat", relevancyScore: 4 },
      { word: "GOAT", relevancyScore: 3 },
    ],
  },
  {
    objective: "Wimbledon",
    category: "Sports",
    taboos: [
      { word: "tennis", relevancyScore: 10 },
      { word: "England", relevancyScore: 9 },
      { word: "grass court", relevancyScore: 8 },
      { word: "Grand Slam", relevancyScore: 7 },
      { word: "strawberries", relevancyScore: 6 },
      { word: "white", relevancyScore: 5 },
      { word: "tournament", relevancyScore: 4 },
      { word: "London", relevancyScore: 3 },
    ],
  },
  // ── Food & Drink (continued) ─────────────────────────────────────────────────
  {
    objective: "Hot Dog",
    category: "Food & Drink",
    taboos: [
      { word: "sausage", relevancyScore: 10 },
      { word: "bun", relevancyScore: 9 },
      { word: "ketchup", relevancyScore: 8 },
      { word: "mustard", relevancyScore: 7 },
      { word: "ballpark", relevancyScore: 6 },
      { word: "fast food", relevancyScore: 5 },
      { word: "grilled", relevancyScore: 4 },
      { word: "American", relevancyScore: 3 },
    ],
  },
  {
    objective: "Spaghetti",
    category: "Food & Drink",
    taboos: [
      { word: "Italy", relevancyScore: 10 },
      { word: "pasta", relevancyScore: 9 },
      { word: "meatballs", relevancyScore: 8 },
      { word: "tomato sauce", relevancyScore: 7 },
      { word: "noodles", relevancyScore: 6 },
      { word: "Bolognese", relevancyScore: 5 },
      { word: "fork", relevancyScore: 4 },
      { word: "dinner", relevancyScore: 3 },
    ],
  },
  {
    objective: "Donut",
    category: "Food & Drink",
    taboos: [
      { word: "fried", relevancyScore: 10 },
      { word: "glazed", relevancyScore: 9 },
      { word: "hole", relevancyScore: 8 },
      { word: "sprinkles", relevancyScore: 7 },
      { word: "police", relevancyScore: 6 },
      { word: "Krispy Kreme", relevancyScore: 5 },
      { word: "frosting", relevancyScore: 4 },
      { word: "bakery", relevancyScore: 3 },
    ],
  },
  {
    objective: "Fried Chicken",
    category: "Food & Drink",
    taboos: [
      { word: "KFC", relevancyScore: 10 },
      { word: "crispy", relevancyScore: 9 },
      { word: "Southern", relevancyScore: 8 },
      { word: "batter", relevancyScore: 7 },
      { word: "fast food", relevancyScore: 6 },
      { word: "Nashville", relevancyScore: 5 },
      { word: "oil", relevancyScore: 4 },
      { word: "juicy", relevancyScore: 3 },
    ],
  },
  {
    objective: "Pho",
    category: "Food & Drink",
    taboos: [
      { word: "Vietnam", relevancyScore: 10 },
      { word: "noodles", relevancyScore: 9 },
      { word: "broth", relevancyScore: 8 },
      { word: "soup", relevancyScore: 7 },
      { word: "beef", relevancyScore: 6 },
      { word: "herbs", relevancyScore: 5 },
      { word: "bowl", relevancyScore: 4 },
      { word: "chopsticks", relevancyScore: 3 },
    ],
  },
  {
    objective: "Nachos",
    category: "Food & Drink",
    taboos: [
      { word: "chips", relevancyScore: 10 },
      { word: "cheese", relevancyScore: 9 },
      { word: "jalapeños", relevancyScore: 8 },
      { word: "guacamole", relevancyScore: 7 },
      { word: "salsa", relevancyScore: 6 },
      { word: "Mexico", relevancyScore: 5 },
      { word: "football", relevancyScore: 4 },
      { word: "movie theater", relevancyScore: 3 },
    ],
  },
  {
    objective: "Cheesecake",
    category: "Food & Drink",
    taboos: [
      { word: "New York", relevancyScore: 10 },
      { word: "cream cheese", relevancyScore: 9 },
      { word: "dessert", relevancyScore: 8 },
      { word: "strawberry", relevancyScore: 7 },
      { word: "graham cracker", relevancyScore: 6 },
      { word: "bake", relevancyScore: 5 },
      { word: "slice", relevancyScore: 4 },
      { word: "sweet", relevancyScore: 3 },
    ],
  },
  {
    objective: "Pad Thai",
    category: "Food & Drink",
    taboos: [
      { word: "Thailand", relevancyScore: 10 },
      { word: "noodles", relevancyScore: 9 },
      { word: "peanuts", relevancyScore: 8 },
      { word: "stir-fry", relevancyScore: 7 },
      { word: "shrimp", relevancyScore: 6 },
      { word: "tofu", relevancyScore: 5 },
      { word: "wok", relevancyScore: 4 },
      { word: "lime", relevancyScore: 3 },
    ],
  },

  // ── Tech (continued) ─────────────────────────────────────────────────────────
  {
    objective: "Instagram",
    category: "Tech",
    taboos: [
      { word: "photos", relevancyScore: 10 },
      { word: "Meta", relevancyScore: 9 },
      { word: "filters", relevancyScore: 8 },
      { word: "influencer", relevancyScore: 7 },
      { word: "followers", relevancyScore: 6 },
      { word: "stories", relevancyScore: 5 },
      { word: "social media", relevancyScore: 4 },
      { word: "reels", relevancyScore: 3 },
    ],
  },
  {
    objective: "Netflix",
    category: "Tech",
    taboos: [
      { word: "streaming", relevancyScore: 10 },
      { word: "binge-watching", relevancyScore: 9 },
      { word: "subscription", relevancyScore: 8 },
      { word: "originals", relevancyScore: 7 },
      { word: "red logo", relevancyScore: 6 },
      { word: "TV shows", relevancyScore: 5 },
      { word: "password sharing", relevancyScore: 4 },
      { word: "movies", relevancyScore: 3 },
    ],
  },
  {
    objective: "Amazon",
    category: "Tech",
    taboos: [
      { word: "Jeff Bezos", relevancyScore: 10 },
      { word: "shopping", relevancyScore: 9 },
      { word: "Prime", relevancyScore: 8 },
      { word: "delivery", relevancyScore: 7 },
      { word: "e-commerce", relevancyScore: 6 },
      { word: "Seattle", relevancyScore: 5 },
      { word: "Alexa", relevancyScore: 4 },
      { word: "warehouse", relevancyScore: 3 },
    ],
  },
  {
    objective: "Zoom",
    category: "Tech",
    taboos: [
      { word: "video call", relevancyScore: 10 },
      { word: "pandemic", relevancyScore: 9 },
      { word: "meeting", relevancyScore: 8 },
      { word: "remote work", relevancyScore: 7 },
      { word: "mute", relevancyScore: 6 },
      { word: "screen share", relevancyScore: 5 },
      { word: "background", relevancyScore: 4 },
      { word: "laptop", relevancyScore: 3 },
    ],
  },
  {
    objective: "Spotify",
    category: "Tech",
    taboos: [
      { word: "music streaming", relevancyScore: 10 },
      { word: "playlists", relevancyScore: 9 },
      { word: "Sweden", relevancyScore: 8 },
      { word: "green logo", relevancyScore: 7 },
      { word: "Wrapped", relevancyScore: 6 },
      { word: "podcast", relevancyScore: 5 },
      { word: "premium", relevancyScore: 4 },
      { word: "shuffle", relevancyScore: 3 },
    ],
  },
  {
    objective: "Uber",
    category: "Tech",
    taboos: [
      { word: "rideshare", relevancyScore: 10 },
      { word: "app", relevancyScore: 9 },
      { word: "driver", relevancyScore: 8 },
      { word: "surge pricing", relevancyScore: 7 },
      { word: "Lyft", relevancyScore: 6 },
      { word: "San Francisco", relevancyScore: 5 },
      { word: "rating", relevancyScore: 4 },
      { word: "fare", relevancyScore: 3 },
    ],
  },

  // ── Movies (continued) ───────────────────────────────────────────────────────
  {
    objective: "The Avengers",
    category: "Movies",
    taboos: [
      { word: "Marvel", relevancyScore: 10 },
      { word: "superheroes", relevancyScore: 9 },
      { word: "Iron Man", relevancyScore: 8 },
      { word: "Captain America", relevancyScore: 7 },
      { word: "Thanos", relevancyScore: 6 },
      { word: "team", relevancyScore: 5 },
      { word: "infinity", relevancyScore: 4 },
      { word: "Thor", relevancyScore: 3 },
    ],
  },
  {
    objective: "Spider-Man",
    category: "Movies",
    taboos: [
      { word: "web", relevancyScore: 10 },
      { word: "Marvel", relevancyScore: 9 },
      { word: "Peter Parker", relevancyScore: 8 },
      { word: "New York", relevancyScore: 7 },
      { word: "superhero", relevancyScore: 6 },
      { word: "mask", relevancyScore: 5 },
      { word: "Tobey Maguire", relevancyScore: 4 },
      { word: "spider", relevancyScore: 3 },
    ],
  },
  {
    objective: "Home Alone",
    category: "Movies",
    taboos: [
      { word: "Macaulay Culkin", relevancyScore: 10 },
      { word: "booby traps", relevancyScore: 9 },
      { word: "Christmas", relevancyScore: 8 },
      { word: "burglars", relevancyScore: 7 },
      { word: "Kevin", relevancyScore: 6 },
      { word: "Chicago", relevancyScore: 5 },
      { word: "family", relevancyScore: 4 },
      { word: "1990", relevancyScore: 3 },
    ],
  },
  {
    objective: "The Lion King",
    category: "Movies",
    taboos: [
      { word: "Simba", relevancyScore: 10 },
      { word: "Mufasa", relevancyScore: 9 },
      { word: "Disney", relevancyScore: 8 },
      { word: "Africa", relevancyScore: 7 },
      { word: "Hakuna Matata", relevancyScore: 6 },
      { word: "Pride Lands", relevancyScore: 5 },
      { word: "animated", relevancyScore: 4 },
      { word: "circle of life", relevancyScore: 3 },
    ],
  },
  {
    objective: "Frozen",
    category: "Movies",
    taboos: [
      { word: "Elsa", relevancyScore: 10 },
      { word: "Disney", relevancyScore: 9 },
      { word: "Let It Go", relevancyScore: 8 },
      { word: "ice", relevancyScore: 7 },
      { word: "Anna", relevancyScore: 6 },
      { word: "Olaf", relevancyScore: 5 },
      { word: "snowman", relevancyScore: 4 },
      { word: "magic", relevancyScore: 3 },
    ],
  },
  {
    objective: "Toy Story",
    category: "Movies",
    taboos: [
      { word: "Woody", relevancyScore: 10 },
      { word: "Buzz Lightyear", relevancyScore: 9 },
      { word: "Pixar", relevancyScore: 8 },
      { word: "toys", relevancyScore: 7 },
      { word: "Andy", relevancyScore: 6 },
      { word: "cowboy", relevancyScore: 5 },
      { word: "animated", relevancyScore: 4 },
      { word: "infinity and beyond", relevancyScore: 3 },
    ],
  },
  {
    objective: "Interstellar",
    category: "Movies",
    taboos: [
      { word: "Christopher Nolan", relevancyScore: 10 },
      { word: "wormhole", relevancyScore: 9 },
      { word: "Matthew McConaughey", relevancyScore: 8 },
      { word: "time dilation", relevancyScore: 7 },
      { word: "space travel", relevancyScore: 6 },
      { word: "NASA", relevancyScore: 5 },
      { word: "2014", relevancyScore: 4 },
      { word: "bookshelf", relevancyScore: 3 },
    ],
  },

  // ── TV Shows (continued) ─────────────────────────────────────────────────────
  {
    objective: "Grey's Anatomy",
    category: "TV Shows",
    taboos: [
      { word: "hospital", relevancyScore: 10 },
      { word: "Meredith Grey", relevancyScore: 9 },
      { word: "Seattle", relevancyScore: 8 },
      { word: "surgery", relevancyScore: 7 },
      { word: "ABC", relevancyScore: 6 },
      { word: "doctors", relevancyScore: 5 },
      { word: "drama", relevancyScore: 4 },
      { word: "relationships", relevancyScore: 3 },
    ],
  },
  {
    objective: "The Mandalorian",
    category: "TV Shows",
    taboos: [
      { word: "Baby Yoda", relevancyScore: 10 },
      { word: "Disney+", relevancyScore: 9 },
      { word: "Star Wars", relevancyScore: 8 },
      { word: "bounty hunter", relevancyScore: 7 },
      { word: "Pedro Pascal", relevancyScore: 6 },
      { word: "Grogu", relevancyScore: 5 },
      { word: "helmet", relevancyScore: 4 },
      { word: "armor", relevancyScore: 3 },
    ],
  },
  {
    objective: "Euphoria",
    category: "TV Shows",
    taboos: [
      { word: "Zendaya", relevancyScore: 10 },
      { word: "HBO", relevancyScore: 9 },
      { word: "teenagers", relevancyScore: 8 },
      { word: "drugs", relevancyScore: 7 },
      { word: "high school", relevancyScore: 6 },
      { word: "Rue", relevancyScore: 5 },
      { word: "glitter makeup", relevancyScore: 4 },
      { word: "drama", relevancyScore: 3 },
    ],
  },
  {
    objective: "Emily in Paris",
    category: "TV Shows",
    taboos: [
      { word: "Netflix", relevancyScore: 10 },
      { word: "Paris", relevancyScore: 9 },
      { word: "fashion", relevancyScore: 8 },
      { word: "American abroad", relevancyScore: 7 },
      { word: "influencer", relevancyScore: 6 },
      { word: "romance", relevancyScore: 5 },
      { word: "France", relevancyScore: 4 },
      { word: "marketing", relevancyScore: 3 },
    ],
  },
  {
    objective: "Ted Lasso",
    category: "TV Shows",
    taboos: [
      { word: "Apple TV+", relevancyScore: 10 },
      { word: "soccer", relevancyScore: 9 },
      { word: "coach", relevancyScore: 8 },
      { word: "AFC Richmond", relevancyScore: 7 },
      { word: "optimism", relevancyScore: 6 },
      { word: "British", relevancyScore: 5 },
      { word: "biscuits", relevancyScore: 4 },
      { word: "Kansas", relevancyScore: 3 },
    ],
  },

  // ── Places (continued) ───────────────────────────────────────────────────────
  {
    objective: "Statue of Liberty",
    category: "Places",
    taboos: [
      { word: "New York", relevancyScore: 10 },
      { word: "torch", relevancyScore: 9 },
      { word: "copper", relevancyScore: 8 },
      { word: "France", relevancyScore: 7 },
      { word: "freedom", relevancyScore: 6 },
      { word: "harbor", relevancyScore: 5 },
      { word: "crown", relevancyScore: 4 },
      { word: "Ellis Island", relevancyScore: 3 },
    ],
  },
  {
    objective: "Colosseum",
    category: "Places",
    taboos: [
      { word: "Rome", relevancyScore: 10 },
      { word: "Italy", relevancyScore: 9 },
      { word: "gladiators", relevancyScore: 8 },
      { word: "ancient", relevancyScore: 7 },
      { word: "arena", relevancyScore: 6 },
      { word: "amphitheater", relevancyScore: 5 },
      { word: "ruins", relevancyScore: 4 },
      { word: "tourists", relevancyScore: 3 },
    ],
  },
  {
    objective: "Big Ben",
    category: "Places",
    taboos: [
      { word: "London", relevancyScore: 10 },
      { word: "England", relevancyScore: 9 },
      { word: "clock tower", relevancyScore: 8 },
      { word: "Parliament", relevancyScore: 7 },
      { word: "Westminster", relevancyScore: 6 },
      { word: "chime", relevancyScore: 5 },
      { word: "Thames", relevancyScore: 4 },
      { word: "landmark", relevancyScore: 3 },
    ],
  },
  {
    objective: "Sydney Opera House",
    category: "Places",
    taboos: [
      { word: "Australia", relevancyScore: 10 },
      { word: "Sydney", relevancyScore: 9 },
      { word: "harbor", relevancyScore: 8 },
      { word: "sails", relevancyScore: 7 },
      { word: "architecture", relevancyScore: 6 },
      { word: "concert", relevancyScore: 5 },
      { word: "performance", relevancyScore: 4 },
      { word: "landmark", relevancyScore: 3 },
    ],
  },
  {
    objective: "Machu Picchu",
    category: "Places",
    taboos: [
      { word: "Peru", relevancyScore: 10 },
      { word: "Inca", relevancyScore: 9 },
      { word: "ruins", relevancyScore: 8 },
      { word: "mountains", relevancyScore: 7 },
      { word: "UNESCO", relevancyScore: 6 },
      { word: "hiking", relevancyScore: 5 },
      { word: "llamas", relevancyScore: 4 },
      { word: "South America", relevancyScore: 3 },
    ],
  },

  // ── Sports (continued) ───────────────────────────────────────────────────────
  {
    objective: "Olympics",
    category: "Sports",
    taboos: [
      { word: "rings", relevancyScore: 10 },
      { word: "gold medal", relevancyScore: 9 },
      { word: "athletes", relevancyScore: 8 },
      { word: "torch", relevancyScore: 7 },
      { word: "international", relevancyScore: 6 },
      { word: "games", relevancyScore: 5 },
      { word: "Paris", relevancyScore: 4 },
      { word: "four years", relevancyScore: 3 },
    ],
  },
  {
    objective: "Tour de France",
    category: "Sports",
    taboos: [
      { word: "cycling", relevancyScore: 10 },
      { word: "France", relevancyScore: 9 },
      { word: "yellow jersey", relevancyScore: 8 },
      { word: "bicycle", relevancyScore: 7 },
      { word: "mountains", relevancyScore: 6 },
      { word: "Lance Armstrong", relevancyScore: 5 },
      { word: "21 stages", relevancyScore: 4 },
      { word: "grueling", relevancyScore: 3 },
    ],
  },
  {
    objective: "FIFA World Cup",
    category: "Sports",
    taboos: [
      { word: "soccer", relevancyScore: 10 },
      { word: "trophy", relevancyScore: 9 },
      { word: "tournament", relevancyScore: 8 },
      { word: "Brazil", relevancyScore: 7 },
      { word: "four years", relevancyScore: 6 },
      { word: "international", relevancyScore: 5 },
      { word: "stadium", relevancyScore: 4 },
      { word: "Qatar", relevancyScore: 3 },
    ],
  },
  {
    objective: "Serena Williams",
    category: "Sports",
    taboos: [
      { word: "tennis", relevancyScore: 10 },
      { word: "Grand Slam", relevancyScore: 9 },
      { word: "GOAT", relevancyScore: 8 },
      { word: "US Open", relevancyScore: 7 },
      { word: "Williams", relevancyScore: 6 },
      { word: "power", relevancyScore: 5 },
      { word: "retirement", relevancyScore: 4 },
      { word: "fashion", relevancyScore: 3 },
    ],
  },
  {
    objective: "Usain Bolt",
    category: "Sports",
    taboos: [
      { word: "sprint", relevancyScore: 10 },
      { word: "fastest", relevancyScore: 9 },
      { word: "Jamaica", relevancyScore: 8 },
      { word: "100 meters", relevancyScore: 7 },
      { word: "world record", relevancyScore: 6 },
      { word: "gold medals", relevancyScore: 5 },
      { word: "lightning bolt", relevancyScore: 4 },
      { word: "Olympics", relevancyScore: 3 },
    ],
  },

  // ── Animals (continued) ──────────────────────────────────────────────────────
  {
    objective: "Koala",
    category: "Animals",
    taboos: [
      { word: "Australia", relevancyScore: 10 },
      { word: "eucalyptus", relevancyScore: 9 },
      { word: "marsupial", relevancyScore: 8 },
      { word: "tree", relevancyScore: 7 },
      { word: "pouch", relevancyScore: 6 },
      { word: "cute", relevancyScore: 5 },
      { word: "bear", relevancyScore: 4 },
      { word: "sleep", relevancyScore: 3 },
    ],
  },
  {
    objective: "Elephant",
    category: "Animals",
    taboos: [
      { word: "trunk", relevancyScore: 10 },
      { word: "tusks", relevancyScore: 9 },
      { word: "Africa", relevancyScore: 8 },
      { word: "large", relevancyScore: 7 },
      { word: "ivory", relevancyScore: 6 },
      { word: "herd", relevancyScore: 5 },
      { word: "memory", relevancyScore: 4 },
      { word: "safari", relevancyScore: 3 },
    ],
  },
  {
    objective: "Penguin",
    category: "Animals",
    taboos: [
      { word: "Antarctica", relevancyScore: 10 },
      { word: "waddle", relevancyScore: 9 },
      { word: "tuxedo", relevancyScore: 8 },
      { word: "ice", relevancyScore: 7 },
      { word: "flightless", relevancyScore: 6 },
      { word: "fish", relevancyScore: 5 },
      { word: "colony", relevancyScore: 4 },
      { word: "black and white", relevancyScore: 3 },
    ],
  },
  {
    objective: "Lion",
    category: "Animals",
    taboos: [
      { word: "mane", relevancyScore: 10 },
      { word: "Africa", relevancyScore: 9 },
      { word: "roar", relevancyScore: 8 },
      { word: "pride", relevancyScore: 7 },
      { word: "king", relevancyScore: 6 },
      { word: "safari", relevancyScore: 5 },
      { word: "cub", relevancyScore: 4 },
      { word: "predator", relevancyScore: 3 },
    ],
  },
  {
    objective: "Giraffe",
    category: "Animals",
    taboos: [
      { word: "long neck", relevancyScore: 10 },
      { word: "Africa", relevancyScore: 9 },
      { word: "spots", relevancyScore: 8 },
      { word: "tall", relevancyScore: 7 },
      { word: "safari", relevancyScore: 6 },
      { word: "leaves", relevancyScore: 5 },
      { word: "zoo", relevancyScore: 4 },
      { word: "hooves", relevancyScore: 3 },
    ],
  },

  // ── Fashion & Brands (continued) ─────────────────────────────────────────────
  {
    objective: "Nike",
    category: "Fashion & Brands",
    taboos: [
      { word: "swoosh", relevancyScore: 10 },
      { word: "Just Do It", relevancyScore: 9 },
      { word: "shoes", relevancyScore: 8 },
      { word: "sportswear", relevancyScore: 7 },
      { word: "Jordan", relevancyScore: 6 },
      { word: "athlete", relevancyScore: 5 },
      { word: "Phil Knight", relevancyScore: 4 },
      { word: "Beaverton", relevancyScore: 3 },
    ],
  },
  {
    objective: "Chanel",
    category: "Fashion & Brands",
    taboos: [
      { word: "Coco", relevancyScore: 10 },
      { word: "France", relevancyScore: 9 },
      { word: "perfume", relevancyScore: 8 },
      { word: "CC logo", relevancyScore: 7 },
      { word: "Paris", relevancyScore: 6 },
      { word: "little black dress", relevancyScore: 5 },
      { word: "luxury", relevancyScore: 4 },
      { word: "fashion house", relevancyScore: 3 },
    ],
  },
  {
    objective: "Rolex",
    category: "Fashion & Brands",
    taboos: [
      { word: "luxury watch", relevancyScore: 10 },
      { word: "Switzerland", relevancyScore: 9 },
      { word: "prestige", relevancyScore: 8 },
      { word: "gold", relevancyScore: 7 },
      { word: "crown logo", relevancyScore: 6 },
      { word: "waterproof", relevancyScore: 5 },
      { word: "Daytona", relevancyScore: 4 },
      { word: "expensive", relevancyScore: 3 },
    ],
  },
  {
    objective: "IKEA",
    category: "Fashion & Brands",
    taboos: [
      { word: "Sweden", relevancyScore: 10 },
      { word: "furniture", relevancyScore: 9 },
      { word: "flat-pack", relevancyScore: 8 },
      { word: "assembly", relevancyScore: 7 },
      { word: "meatballs", relevancyScore: 6 },
      { word: "Scandinavian", relevancyScore: 5 },
      { word: "blue yellow", relevancyScore: 4 },
      { word: "maze store", relevancyScore: 3 },
    ],
  },

  // ── Science & Nature (continued) ─────────────────────────────────────────────
  {
    objective: "DNA",
    category: "Science & Nature",
    taboos: [
      { word: "double helix", relevancyScore: 10 },
      { word: "genetics", relevancyScore: 9 },
      { word: "chromosomes", relevancyScore: 8 },
      { word: "blueprint", relevancyScore: 7 },
      { word: "cells", relevancyScore: 6 },
      { word: "Watson and Crick", relevancyScore: 5 },
      { word: "sequence", relevancyScore: 4 },
      { word: "biology", relevancyScore: 3 },
    ],
  },
  {
    objective: "Rainbow",
    category: "Science & Nature",
    taboos: [
      { word: "colors", relevancyScore: 10 },
      { word: "rain", relevancyScore: 9 },
      { word: "arc", relevancyScore: 8 },
      { word: "sky", relevancyScore: 7 },
      { word: "spectrum", relevancyScore: 6 },
      { word: "ROYGBIV", relevancyScore: 5 },
      { word: "pot of gold", relevancyScore: 4 },
      { word: "prism", relevancyScore: 3 },
    ],
  },
  {
    objective: "Tornado",
    category: "Science & Nature",
    taboos: [
      { word: "twister", relevancyScore: 10 },
      { word: "wind", relevancyScore: 9 },
      { word: "funnel", relevancyScore: 8 },
      { word: "Midwest", relevancyScore: 7 },
      { word: "storm chaser", relevancyScore: 6 },
      { word: "Dorothy", relevancyScore: 5 },
      { word: "Kansas", relevancyScore: 4 },
      { word: "destruction", relevancyScore: 3 },
    ],
  },

  // ── Mythology & Folklore (continued) ─────────────────────────────────────────
  {
    objective: "Dragon",
    category: "Mythology & Folklore",
    taboos: [
      { word: "fire", relevancyScore: 10 },
      { word: "wings", relevancyScore: 9 },
      { word: "scales", relevancyScore: 8 },
      { word: "medieval", relevancyScore: 7 },
      { word: "fantasy", relevancyScore: 6 },
      { word: "Game of Thrones", relevancyScore: 5 },
      { word: "mythical", relevancyScore: 4 },
      { word: "treasure", relevancyScore: 3 },
    ],
  },
  {
    objective: "Werewolf",
    category: "Mythology & Folklore",
    taboos: [
      { word: "full moon", relevancyScore: 10 },
      { word: "wolf", relevancyScore: 9 },
      { word: "transformation", relevancyScore: 8 },
      { word: "silver bullet", relevancyScore: 7 },
      { word: "howl", relevancyScore: 6 },
      { word: "monster", relevancyScore: 5 },
      { word: "human", relevancyScore: 4 },
      { word: "Halloween", relevancyScore: 3 },
    ],
  },
];

async function main() {
  const existing = await db
    .select({
      objective: schema.wordCards.objective,
      category: schema.wordCards.category,
    })
    .from(schema.wordCards);

  const existingSet = new Set(
    existing.map((r) => `${r.objective}|${r.category}`),
  );

  const toInsert = cards.filter(
    (c) => !existingSet.has(`${c.objective}|${c.category}`),
  );

  if (toInsert.length === 0) {
    console.log(
      `All ${cards.length} cards already exist in the database. Nothing to insert.`,
    );
    return;
  }

  await db.insert(schema.wordCards).values(
    toInsert.map((c) => ({
      objective: c.objective,
      category: c.category,
      taboos: c.taboos,
      source: "system" as const,
    })),
  );

  console.log(
    `Inserted ${toInsert.length} new cards. Skipped ${cards.length - toInsert.length} already existing.`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
